version: '3.6'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile.api
    environment:
      - DISCORD_TOKEN=DYyNzI1MTcwNzI5MDU4MzQ0.GXVHou.1pbaHwxrx4xk8sZUUwBq-zsV_d4VspW4PExwpE
      - SAVE_FILE=./SAVES.json
    volumes:
      - ./data:/data:rw